<?php


namespace app\admin\facade;


use think\Facade;


/**
 * @see app\admin\common\AddRoute
 * @package app\admin\facade
 * @mixin app\admin\common\AddRoute
 * @method static \app\admin\common\AddRoute getController() 获取控制器列表
 * @method static \app\admin\common\AddRoute getOneController() 获取一个控制器的数据
 * @method static \app\admin\common\AddRoute getControllerName() 获取目录名称
 * @method static \app\admin\common\AddRoute getSon($data,$pid) 获取子类id
 * @method static \app\admin\common\Menu getControllerByName($name)  根据名称查询目录
 */

class AddRoute extends Facade
{

    protected static function getFacadeClass()
    {
        parent::getFacadeClass(); // TODO: Change the autogenerated stub
        return 'app\admin\common\AddRoute';
    }
}