<?php


namespace app\admin\facade;


use think\Facade;


/**
 * @see app\admin\common\Role
 * @package app\admin\facade
 * @mixin app\admin\common\Role
 * @method static \app\admin\common\Role getRoleList() 获取管理员列表信息
 * @method static \app\admin\common\Role getOneData($id) 根据id获取角色信息
 * @method static \app\admin\common\Role getMenuTree() 获取权限树
 * @method static \app\admin\common\Role getAready() 获取选择项
 */
class Role extends Facade
{

    protected static function getFacadeClass()
    {
        parent::getFacadeClass(); // TODO: Change the autogenerated stub
        return \app\admin\common\Role::class;
    }
}