<?php


namespace app\admin\facade;


use think\Facade;


/**
 * @see app\admin\common\User
 * @package app\admin\facade
 * @mixin app\admin\common\User
 * @method static \app\admin\common\User getUserList($page,$limit) 获取用户列表getUserList
 * @method static \app\admin\common\User getRole() 获取权限名称getUserData
 * @method static \app\admin\common\User getUserData($id) 根据id获取一个用户信息
 */
class User extends Facade
{
    protected static function getFacadeClass()
    {
        parent::getFacadeClass(); // TODO: Change the autogenerated stub
        return 'app\admin\common\User';
    }

}